### ISSUE TITLE
run: add -m|--message (or -d|--description)

### ISSUE THREAD

**Issue by yarikoptic** [vsoch/qme#27]
Especially since there is `search` it would be great if I could annotate my runs.  Such message (git inspired) or description is probably what to include in `ls` output

**Comment by vsoch** [comment]
Oh yeah that's a cool idea! Smells like datalad. Or teen spirit.

**Comment by vsoch** [comment]
It would need to go at the top level of the client so it doesn't conflict with a command that might have the same flag. But then it would only be parsed for run (or re-run).

**Comment by vsoch** [comment]
Here is an example of this working:
```
$ qme --message 'I am echoing a thing' run echo hello
Database: sqlite
[shell-9817744f-77ae-4e8b-ac2e-2e326bc11d7b][returncode: 0]

$ qme get
Database: sqlite
{
    "executor": "shell",
    "uid": "shell-9817744f-77ae-4e8b-ac2e-2e326bc11d7b",
    "data": {
        "pwd": "/home/vanessa/Desktop/Code/qme",
        "user": "vanessa",
        "timestamp": "2020-05-29 14:24:10.050944",
        "message": "I am echoing a thing",
        "output": [
            "hello\n"
        ],
        "error": [],
        "returncode": 0,
        "pid": 30157,
        "cmd": [
            "echo",
            "hello"
        ],
        "status": "complete"
    },
    "command": "echo hello"
}
```

**Comment by vsoch** [comment]
And in interface

![image](https://user-images.githubusercontent.com/814322/83302916-6395ba00-a1b9-11ea-9edc-c7256ebce4b3.png)

**Comment by vsoch** [comment]
Added with #32
