### ISSUE TITLE
I am sad: I am no longer wanted as a collaborator :-(

### ISSUE THREAD

**Issue by yarikoptic** [vsoch/qme#33]
;-)
received an invitation but following the link resulted in 

 
@yarikoptic 
Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account.

**Comment by vsoch** [comment]
Ah don't be sad, that wasn't my intention! I was looking for the different levels of contribution and couldn't find them, and I think those levels are only for org repos. I can definitely add you, and if it's okay with you, I'd like to take charge of doing final merges, and there is absolutely never a case to push to master. Is that ok?

**Comment by yarikoptic** [comment]
Ah sure, I am not looking for more superpowers. Issue was just to report that I tried and it failed, didn't want to not let it go unnoticed if it was not intentional
